export default function ShortcutsPanel() {
  return (
    <div id="shortcuts-panel" className="hidden fixed bg-white p-4 border border-gray-200 shadow-2xl rounded-lg w-[500px] max-w-[95vw] z-[1000] cursor-default max-h-[80vh] overflow-y-auto" onClick={(e) => e.stopPropagation()}>
        <div className="flex justify-between items-center mb-3 border-b pb-2">
            <h4 className="text-sm font-bold text-gray-700 flex items-center gap-2"><i data-lucide="keyboard" className="w-4 h-4"></i> <span data-i18n="txt_023">Atajos de teclado</span></h4>
            <button id="btn-close-shortcuts" className="text-gray-400 hover:text-gray-600"><i data-lucide="x" className="w-5 h-5"></i></button>
        </div>
        <div className="grid grid-cols-1 sm:grid-cols-2 gap-x-4 gap-y-2 text-[11px] text-gray-600">
            {/* Columna 1 */}
            <ul className="flex flex-col gap-2">
                <li className="flex items-center gap-2"><i data-lucide="play" className="w-3.5 h-3.5 shrink-0 text-gray-400"></i><kbd className="bg-gray-100 border px-1.5 py-0.5 rounded font-mono shadow-sm"><span data-i18n="txt_024">Espacio</span></kbd> <span className="truncate"><span data-i18n="txt_025">Reproducir / Pausar</span></span></li>
                <li className="flex items-center gap-2"><i data-lucide="settings" className="w-3.5 h-3.5 shrink-0 text-gray-400"></i><kbd className="bg-gray-100 border px-1.5 py-0.5 rounded font-mono shadow-sm">A</kbd> <span className="truncate"><span data-i18n="txt_026">Ajustes</span></span></li>
                <li className="flex items-center gap-2"><i data-lucide="ruler" className="w-3.5 h-3.5 shrink-0 text-gray-400"></i><kbd className="bg-gray-100 border px-1.5 py-0.5 rounded font-mono shadow-sm">B</kbd> <span className="truncate"><span data-i18n="txt_027">Omitir lectura sobre los Bordes</span></span></li>
                <li className="flex items-center gap-2"><i data-lucide="list" className="w-3.5 h-3.5 shrink-0 text-gray-400"></i><kbd className="bg-gray-100 border px-1.5 py-0.5 rounded font-mono shadow-sm">C</kbd> <span className="truncate"><span data-i18n="txt_028">Índice de Capítulos</span></span></li>
                <li className="flex items-center gap-2"><i data-lucide="upload" className="w-3.5 h-3.5 shrink-0 text-gray-400"></i><kbd className="bg-gray-100 border px-1.5 py-0.5 rounded font-mono shadow-sm">D</kbd> <span className="truncate"><span data-i18n="txt_029">Cargar nuevo archivo</span></span></li>
                <li className="flex items-center gap-2"><i data-lucide="book-open" className="w-3.5 h-3.5 shrink-0 text-gray-400"></i><kbd className="bg-gray-100 border px-1.5 py-0.5 rounded font-mono shadow-sm">E</kbd> <span className="truncate"><span data-i18n="txt_030">Activar modo Estudio</span></span></li>
                <li className="flex items-center gap-2"><i data-lucide="image" className="w-3.5 h-3.5 shrink-0 text-gray-400"></i><kbd className="bg-gray-100 border px-1.5 py-0.5 rounded font-mono shadow-sm">F</kbd> <span className="truncate"><span data-i18n="txt_031">Índice de Figuras</span></span></li>
                <li className="flex items-center gap-2"><i data-lucide="eye-off" className="w-3.5 h-3.5 shrink-0 text-gray-400"></i><kbd className="bg-gray-100 border px-1.5 py-0.5 rounded font-mono shadow-sm">G</kbd> <span className="truncate"><span data-i18n="txt_032">Omitir gráficos</span></span></li>
                <li className="flex items-center gap-2"><i data-lucide="sparkles" className="w-3.5 h-3.5 shrink-0 text-gray-400"></i><kbd className="bg-gray-100 border px-1.5 py-0.5 rounded font-mono shadow-sm">H</kbd> <span className="truncate"><span data-i18n="txt_033">Abrir Chat de IA</span></span></li>
                <li className="flex items-center gap-2"><i data-lucide="list-ordered" className="w-3.5 h-3.5 shrink-0 text-gray-400"></i><kbd className="bg-gray-100 border px-1.5 py-0.5 rounded font-mono shadow-sm">I</kbd> <span className="truncate"><span data-i18n="txt_034">Activar índice Dinámico</span></span></li>
                <li className="flex items-center gap-2"><i data-lucide="keyboard" className="w-3.5 h-3.5 shrink-0 text-gray-400"></i><kbd className="bg-gray-100 border px-1.5 py-0.5 rounded font-mono shadow-sm">J</kbd> <span className="truncate"><span data-i18n="txt_035">Abrir panel de atajos</span></span></li>
                <li className="flex items-center gap-2"><i data-lucide="radio" className="w-3.5 h-3.5 shrink-0 text-gray-400"></i><kbd className="bg-gray-100 border px-1.5 py-0.5 rounded font-mono shadow-sm">K</kbd> <span className="truncate"><span data-i18n="txt_038">Conversación con Karai</span></span></li>
                <li className="flex items-center gap-2"><i data-lucide="link-2" className="w-3.5 h-3.5 shrink-0 text-gray-400"></i><kbd className="bg-gray-100 border px-1.5 py-0.5 rounded font-mono shadow-sm">L</kbd> <span className="truncate"><span data-i18n="txt_036">Omitir lectura de Links</span></span></li>
                <li className="flex items-center gap-2"><i data-lucide="mic" className="w-3.5 h-3.5 shrink-0 text-gray-400"></i><kbd className="bg-gray-100 border px-1.5 py-0.5 rounded font-mono shadow-sm">M</kbd> <span className="truncate"><span data-i18n="txt_037">Activar Micrófono IA</span></span></li>
                <li className="flex items-center gap-2"><i data-lucide="compass" className="w-3.5 h-3.5 shrink-0 text-gray-400"></i><kbd className="bg-gray-100 border px-1.5 py-0.5 rounded font-mono shadow-sm">N</kbd> <span className="truncate"><span data-i18n="txt_061">Navegador por voz (Brújula)</span></span></li>
            </ul>
            {/* Columna 2 */}
            <ul className="flex flex-col gap-2">
                <li className="flex items-center gap-2"><i data-lucide="volume-2" className="w-3.5 h-3.5 shrink-0 text-gray-400"></i><kbd className="bg-gray-100 border px-1.5 py-0.5 rounded font-mono shadow-sm">O</kbd> <span className="truncate"><span data-i18n="txt_060">Opciones de audio</span></span></li>
                <li className="flex items-center gap-2"><i data-lucide="volume-x" className="w-3.5 h-3.5 shrink-0 text-gray-400"></i><kbd className="bg-gray-100 border px-1.5 py-0.5 rounded font-mono shadow-sm"><span data-i18n="txt_039">Esc</span></kbd> <span className="truncate"><span data-i18n="txt_040">Detener sonido de IA</span></span></li>
                <li className="flex items-center gap-2"><i data-lucide="parentheses" className="w-3.5 h-3.5 shrink-0 text-gray-400"></i><kbd className="bg-gray-100 border px-1.5 py-0.5 rounded font-mono shadow-sm">P</kbd> <span className="truncate"><span data-i18n="txt_041">Activar texto paréntesis</span></span></li>
                <li className="flex items-center gap-2"><i data-lucide="circle-help" className="w-3.5 h-3.5 shrink-0 text-gray-400"></i><kbd className="bg-gray-100 border px-1.5 py-0.5 rounded font-mono shadow-sm">Q</kbd> <span className="truncate"><span data-i18n="txt_042">Abrir ayuda</span></span></li>
                <li className="flex items-center gap-2"><i data-lucide="scan" className="w-3.5 h-3.5 shrink-0 text-gray-400"></i><kbd className="bg-gray-100 border px-1.5 py-0.5 rounded font-mono shadow-sm">R</kbd> <span className="truncate"><span data-i18n="txt_043">Modo Rastreador</span></span></li>
                <li className="flex items-center gap-2"><i data-lucide="arrow-down-up" className="w-3.5 h-3.5 shrink-0 text-gray-400"></i><kbd className="bg-gray-100 border px-1.5 py-0.5 rounded font-mono shadow-sm">S</kbd> <span className="truncate"><span data-i18n="txt_044">Activar auto-Scroll</span></span></li>
                <li className="flex items-center gap-2"><i data-lucide="languages" className="w-3.5 h-3.5 shrink-0 text-gray-400"></i><kbd className="bg-gray-100 border px-1.5 py-0.5 rounded font-mono shadow-sm">T</kbd> <span className="truncate"><span data-i18n="txt_045">Activar Traducción</span></span></li>
                <li className="flex items-center gap-2"><i data-lucide="closed-caption" className="w-3.5 h-3.5 shrink-0 text-gray-400"></i><kbd className="bg-gray-100 border px-1.5 py-0.5 rounded font-mono shadow-sm">U</kbd> <span className="truncate"><span data-i18n="txt_046">Activar Subtítulos</span></span></li>
                <li className="flex items-center gap-2"><i data-lucide="volume-2" className="w-3.5 h-3.5 shrink-0 text-gray-400"></i><kbd className="bg-gray-100 border px-1.5 py-0.5 rounded font-mono shadow-sm">V</kbd> <span className="truncate"><span data-i18n="txt_047">Seleccionar voz</span></span></li>
                <li className="flex items-center gap-2"><i data-lucide="earth" className="w-3.5 h-3.5 shrink-0 text-gray-400"></i><kbd className="bg-gray-100 border px-1.5 py-0.5 rounded font-mono shadow-sm">W</kbd> <span className="truncate"><span data-i18n="txt_048">Todos los idiomas</span></span></li>
                <li className="flex items-center gap-2"><i data-lucide="move-horizontal" className="w-3.5 h-3.5 shrink-0 text-gray-400"></i><kbd className="bg-gray-100 border px-1.5 py-0.5 rounded font-mono shadow-sm">X</kbd> <span className="truncate"><span data-i18n="txt_049">Ajustar al ancho</span></span></li>
                <li className="flex items-center gap-2"><i data-lucide="move-vertical" className="w-3.5 h-3.5 shrink-0 text-gray-400"></i><kbd className="bg-gray-100 border px-1.5 py-0.5 rounded font-mono shadow-sm">Y</kbd> <span className="truncate"><span data-i18n="txt_050">Ajustar al alto</span></span></li>
                <li className="flex items-center gap-2"><i data-lucide="expand" className="w-3.5 h-3.5 shrink-0 text-gray-400"></i><kbd className="bg-gray-100 border px-1.5 py-0.5 rounded font-mono shadow-sm">Z</kbd> <span className="truncate"><span data-i18n="txt_051">Pantalla completa</span></span></li>
                <li className="flex items-center gap-2"><i data-lucide="zoom-in" className="w-3.5 h-3.5 shrink-0 text-gray-400"></i><kbd className="bg-gray-100 border px-1.5 py-0.5 rounded font-mono shadow-sm"><span data-i18n="txt_052">Ctrl +/-</span></kbd> <span className="truncate"><span data-i18n="txt_053">Acercar / alejar zoom</span></span></li>
                <li className="flex items-center gap-2"><i data-lucide="mouse" className="w-3.5 h-3.5 shrink-0 text-gray-400"></i><kbd className="bg-gray-100 border px-1.5 py-0.5 rounded font-mono shadow-sm"><span data-i18n="txt_056">Ctrl+Rueda</span></kbd> <span className="truncate"><span data-i18n="txt_057">Zoom con el mouse</span></span></li>
            </ul>
        </div>
    </div>
  );
}
